### ISSUE TITLE
Adding fonts

### ISSUE THREAD

**Issue by erhard** [ricardobalk/docker#1]
Is there a way to add additional fonts to the container of Scribus ?   I use the container on a Mac it works great except the fact that the fonts are not used from the hosting machine. Well perhaps the fonts dir can be somehow injected mounted etc. Any ideas ?

**Comment by ricardobalk** [comment]
Not sure, but given the following circumstances
- User fonts on macOS are in `$HOME/Library/Fonts` (`$HOME` being `/Users/username` on macOS)
- User fonts on Ubuntu are in `$HOME/.fonts` (`$HOME` being `/home/scribus` inside the container)

You will likely have to add `-v $HOME/Library/Fonts:/home/scribus/.fonts:ro` to the Docker command (`ro` for read-only).

Let me know if that works, otherwise I'll have a look into it. I'm having a MacBook Pro as well since a month 🎉

**Comment by erhard** [comment]
Works great. Your container is the best way to run Scribus scripts on Mac m1 !
Thanks 
👍
